name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 3 * * 1' # Jeden Montag um 03:00 UTC
  workflow_dispatch:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: |
          TAG_TS=$(date +%s)
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_TAG=${TAG_TS}" >> $GITHUB_OUTPUT
          echo "REPO_LC=${REPO_LC}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.REPO_LC }}:${{ steps.vars.outputs.IMAGE_TAG }} -t ghcr.io/${{ steps.vars.outputs.REPO_LC }}:latest .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.REPO_LC }}:${{ steps.vars.outputs.IMAGE_TAG }}
          docker push ghcr.io/${{ steps.vars.outputs.REPO_LC }}:latest

      - name: Prune old images (keep last 7)
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 7
